[DATALAD] Recorded changes

diff --git a/.github/workflows/run_tests_matlab.yml b/.github/workflows/run_tests_matlab.yml
--- a/.github/workflows/run_tests_matlab.yml
+++ b/.github/workflows/run_tests_matlab.yml
@@ -53,14 +53,20 @@ jobs:
         with:
           command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;
 
-      - name: Run tests
+      - name: Check logs unix
+        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+        run: grep -q 0 test_report.log || { echo "Some tests failed. Check the 'Run tests' step to know which ones." >&2; exit 1; }
+      - name: Check logs windows
+        if: matrix.os == 'windows-latest'
         run: |
-          cat test_report.log | grep 0
+          if (-not (Get-Content test_report.log | Select-String -Pattern "0")) {
+            throw "Some tests failed.  Check the 'Run tests' step to know which ones."
+          }
 
       - name: Code coverage
         uses: codecov/codecov-action@v3
         with:
-          file: coverage.xml # optional
-          flags: unittests # optional
-          name: codecov-umbrella # optional
-          fail_ci_if_error: false # optional (default = false)
+          file: coverage.xml 
+          flags: matlab
+          name: codecov-umbrella 
+          fail_ci_if_error: false 
